# Generated by Django 6.0.7 on 2026-07-29 11:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('availability_available', models.BooleanField(default=True, help_text='Toggles the availability indicator shown in the contact section.', verbose_name='Currently available')),
                ('availability_text', models.CharField(blank=True, default='Available for new opportunities', max_length=140)),
                ('social_links', wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('github', 'GitHub'), ('gitlab', 'GitLab'), ('linkedin', 'LinkedIn'), ('x', 'X / Twitter'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('dribbble', 'Dribbble'), ('behance', 'Behance'), ('codepen', 'CodePen'), ('stackoverflow', 'Stack Overflow'), ('medium', 'Medium'), ('devto', 'DEV Community'), ('mastodon', 'Mastodon'), ('discord', 'Discord'), ('bluesky', 'Bluesky'), ('reddit', 'Reddit')]}), 1: ('wagtail.blocks.URLBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Leave blank to use the platform name.', 'max_length': 60, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('platform', 0), ('url', 1), ('label', 2)]], {})}, help_text='Social / profile links shown in the footer and contact section.')),
                ('cv_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='CV / résumé')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_links', wagtail.fields.StreamField([('link', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use the linked page's title.", 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Internal page', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use this for project subdomains, e.g. https://myapp.example.com', 'label': 'External URL', 'required': False}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document (e.g. your CV)', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Jump to a section on the target page, e.g. "contact".', 'max_length': 60, 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary — solid accent'), ('secondary', 'Secondary — outlined'), ('ghost', 'Ghost — text only')]}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'No icon'), ('arrow-up-right', 'Arrow (up-right)'), ('arrow-right', 'Arrow (right)'), ('arrow-down', 'Arrow (down)'), ('download', 'Download'), ('mail', 'Mail'), ('phone', 'Phone'), ('map-pin', 'Location pin'), ('calendar', 'Calendar'), ('briefcase', 'Briefcase'), ('graduation', 'Graduation cap'), ('code', 'Code'), ('link', 'Link'), ('globe', 'Globe'), ('external', 'External window'), ('layers', 'Layers'), ('spark', 'Spark'), ('check', 'Check'), ('search', 'Search'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('linkedin', 'LinkedIn'), ('x', 'X / Twitter'), ('telegram', 'Telegram')], 'required': False}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('external_url', 2), ('document', 3), ('anchor', 4), ('style', 5), ('icon', 6), ('open_in_new_tab', 7)]], {})}, help_text='Links shown in the main site header.')),
                ('footer_note', models.CharField(blank=True, help_text='Short line shown in the footer, e.g. "Built with Django & Wagtail."', max_length=200)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Navigation',
            },
        ),
        migrations.CreateModel(
            name='SiteBrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Portfolio', max_length=80)),
                ('tagline', models.CharField(blank=True, help_text='Short line shown in the browser tab / share previews.', max_length=160)),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('logo', models.ForeignKey(blank=True, help_text='Shown in the header. Falls back to the site name if empty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('social_share_image', models.ForeignKey(blank=True, help_text='Default image used when pages are shared, unless a page sets its own.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Site branding',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('url', models.URLField(blank=True, help_text="The technology's homepage.")),
                ('category', models.CharField(blank=True, help_text='e.g. "Backend", "Frontend", "DevOps".', max_length=60)),
                ('logo', models.ForeignKey(blank=True, help_text='A square logo/mark, ideally an SVG or transparent PNG.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=140)),
                ('company', models.CharField(blank=True, max_length=140)),
                ('quote', models.TextField()),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
